"""
Export utility for Fieldbook notebook entries (Markdown & JSON exports).
"""

import json
from datetime import datetime
try:
    from datetime import timezone
    def get_utc_now_iso():
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    def get_utc_now_str():
        return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
except ImportError:
    def get_utc_now_iso():
        return datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    def get_utc_now_str():
        return datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

def export_to_json(entries, pretty=True):
    """
    Exports a list of NotebookEntry objects to a JSON string.
    """
    raw_data = []
    for entry in entries:
        if hasattr(entry, "to_dict"):
            raw_data.append(entry.to_dict())
        elif isinstance(entry, dict):
            raw_data.append(entry)

    if pretty:
        return json.dumps({"version": 1, "exported_at": get_utc_now_iso(), "entries": raw_data}, indent=2, ensure_ascii=False)
    else:
        return json.dumps({"version": 1, "exported_at": get_utc_now_iso(), "entries": raw_data}, ensure_ascii=False)

def export_to_markdown(entries, store=None, title="Fieldbook Research Report"):
    """
    Exports a list of NotebookEntry objects to a formatted Markdown report.
    """
    lines = []
    lines.append("# " + str(title))
    lines.append("")
    lines.append("*Generated by Fieldbook Research Notebook on " + get_utc_now_str() + "*")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not entries:
        lines.append("*No entries found.*")
        return "\n".join(lines)

    for idx, entry in enumerate(entries, 1):
        e_dict = entry.to_dict() if hasattr(entry, "to_dict") else entry

        entry_type = e_dict.get("entry_type", "NOTE")
        target = e_dict.get("target", "")
        tags = e_dict.get("tags", [])
        text = e_dict.get("text", "")
        created_at = e_dict.get("created_at", "")
        updated_at = e_dict.get("updated_at", "")
        pinned = e_dict.get("pinned", False)
        linked_requests = e_dict.get("linked_requests", [])
        entry_id = e_dict.get("id", "")

        pin_str = " 📌 [PINNED]" if pinned else ""
        lines.append("## %d. [%s] %s%s" % (idx, entry_type, target or "General", pin_str))
        lines.append("")

        meta_parts = []
        if target:
            meta_parts.append("**Target:** `%s`" % target)
        if tags:
            meta_parts.append("**Tags:** " + ", ".join(["`" + str(t) + "`" for t in tags]))
        meta_parts.append("**Created:** %s" % created_at)
        meta_parts.append("**ID:** `%s`" % entry_id)

        lines.append(" | ".join(meta_parts))
        lines.append("")

        lines.append("### Content")
        lines.append(text)
        lines.append("")

        if linked_requests:
            lines.append("### Linked Requests (%d)" % len(linked_requests))
            for r_idx, req in enumerate(linked_requests, 1):
                if not isinstance(req, dict):
                    continue
                method = req.get("method", "GET")
                url = req.get("url", "")
                label = req.get("label", "")
                status = req.get("raw_response_status", "")
                raw_req = req.get("raw_request", "")
                raw_resp = req.get("raw_response_headers_and_body_or_reference", "")

                lines.append("#### Request #req:%d - %s" % (r_idx, label or url or method))
                lines.append("- **Method:** `%s`" % method)
                lines.append("- **URL:** `%s`" % url)
                if status:
                    lines.append("- **Status:** `%s`" % str(status))

                if raw_req:
                    lines.append("")
                    lines.append("```http")
                    lines.append(str(raw_req).strip())
                    lines.append("```")

                if raw_resp:
                    lines.append("")
                    lines.append("```http")
                    lines.append(str(raw_resp).strip())
                    lines.append("```")
                lines.append("")

        if store and hasattr(store, "get_backlinks"):
            backlinks = store.get_backlinks(entry_id)
            if backlinks:
                lines.append("### Referenced By (%d)" % len(backlinks))
                for b in backlinks:
                    b_target = b.target or "General"
                    lines.append("- [%s] %s (ID: `%s`)" % (b.entry_type, b_target, b.id))
                lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)
